In [61]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (accuracy_score, precision_score,
                              recall_score)

# Load data
df = pd.read_csv('heart_disease.csv')

In [4]:
# Task 1

print(df.shape)
df.head()


# This is a classification problem and binary because we are predicting whether or not a patient has heart disease
# This can only be has heart disease or does not have heart disesase

(270, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0

In [22]:
# Task 2

disease_yes = round(((df['target'].value_counts()[1]) / df.shape[0]) * 100, 1)
disease_no = round(((df['target'].value_counts()[0]) / df.shape[0]) * 100, 1)

print(f"Patients with heart disease: {disease_yes}%")
print(f"Patients without heart disease: {disease_no}%")

# A lazy model would get 55.6% of guesses correct
# For medical diagnosis, it's much more dangerous to miss a diagnosis than to misidentify one

Patients with heart disease: 44.4%
Patients without heart disease: 55.6%

In [28]:
# Task 3

X = df[['age', 'trestbps', 'chol', 'thalach']]
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [56]:
# Task 4

model = LogisticRegression()
model.fit(X_train, y_train)

pred = pd.DataFrame(model.predict(X_test))
perc = pd.DataFrame(model.predict_proba(X_test))

perc_med = perc.median()

print(f"Prediction: {pred}")

print(f"Predicted % of heart disease: {perc_med[0]:.2}%")

Prediction:     0
0   0
1   0
2   0
3   0
4   1
5   0
6   0
7   0
8   0
9   1
10  1
11  0
12  1
13  1
14  1
15  0
16  1
17  0
18  0
19  0
20  1
21  0
22  1
23  0
24  0
25  1
26  0
27  0
28  0
29  0
30  0
31  0
32  0
33  0
34  0
35  1
36  0
37  0
38  1
39  1
40  1
41  0
42  1
43  0
44  0
45  0
46  0
47  1
48  1
49  0
50  1
51  0
52  0
53  1
Predicted % of heart disease: 0.59%

In [59]:
# Task 5

print(pred.head(5))
perc.head(5)

# Very sure about the 3rd patient with 83% and unsure about the 1st and 2nd, both close to 50%

   0
0  0
1  0
2  0
3  0
4  1

          0         1
0  0.589066  0.410934
1  0.536894  0.463106
2  0.839802  0.160198
3  0.744548  0.255452
4  0.421834  0.578166

In [ ]:
# Task 6

model = DecisionTreeClassifier(max_depth=10, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_train = model.predict(X_train)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Training Data Accuracy: {accuracy_score(y_train, y_pred_train)}")

# DecisionTree scores very high on training data compared to test data because it becomes overfit

Accuracy: 0.5370370370370371
Training Data Accuracy: 0.9675925925925926